version: '3.4'

networks:
  default:
    driver: bridge

services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./app/:/app
    command: ["sh", "-c", "python /app/init_db.py && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - default
