version: '3.4'

networks:
  default:
    driver: bridge

services:
  api:
    build: ./app
    networks:
      - default
    volumes:
      - ./app:/app                          # Monte les fichiers locaux dans le conteneur API
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  frontend:
    build: ./frontend
    networks:
      - default
    volumes:
      - ./frontend:/app                     # Monte les fichiers locaux pour le développement frontend
      - /app/node_modules                   # Garde node_modules dans un volume séparé pour éviter les problèmes de permissions
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always

volumes:
  postgres_data:
